import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from 'node:module';
import fs from "node:fs";
import path from "node:path";

// ==================== Constants ====================
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outDir = "dist";


// Path constants
const cssRoot = path.join(process.cwd(), 'src');
const cssDest = path.join(process.cwd(), outDir, 'styles.css');

// ==================== Helpers ====================
// Recursively collect every CSS file below src
function collectCssFiles(dir) {
	const results = [];
	if (!fs.existsSync(dir)) return results;
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	for (const entry of entries) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			results.push(...collectCssFiles(full));
		} else if (entry.isFile() && entry.name.endsWith('.css')) {
			results.push(full);
		}
	}
	return results;
}

// ==================== Build steps ====================
// Build the CSS: concatenate every CSS file below src into dist/styles.css
// - dev: concatenate and keep the comments, so the output stays readable
// - production: minify through esbuild and drop the comments
async function buildCSS() {
	if (!fs.existsSync(cssRoot)) {
		console.warn('⚠ CSS root directory does not exist: src');
		return;
	}

	const cssFiles = collectCssFiles(cssRoot).sort();
	if (!cssFiles.length) {
		// Without any CSS file, remove a styles.css left over in dist.
		if (fs.existsSync(cssDest)) {
			fs.unlinkSync(cssDest);
			console.log('✓ Removed dist/styles.css (no CSS files in the source directory)');
		}
		return;
	}

	const parts = cssFiles.map((file) => {
		const rel = path.relative(process.cwd(), file);
		const content = fs.readFileSync(file, 'utf8');
		return `/* ${rel} */\n${content}`;
	});
	const combinedCss = parts.join('\n\n');

	try {
		// Make sure the output directory exists.
		fs.mkdirSync(path.join(process.cwd(), outDir), { recursive: true });

		// Transform the CSS through esbuild.
		// - production: minify and drop the comments
		// - dev: no minification, syntax check only
		const result = await esbuild.transform(combinedCss, {
			loader: 'css',
			minify: prod,
			sourcemap: false,
		});

		fs.writeFileSync(cssDest, result.code);
	} catch (error) {
		// On a transform failure, fall back to the unminified version.
		console.error('Error while building the CSS; fell back to the unminified version:', error);
		fs.writeFileSync(cssDest, combinedCss);
	}

	// console.log(`✓ CSS bundled: ${cssDest} (${cssFiles.length} files)`);
}

// Copy manifest.json into the output directory
function copyManifest() {
	const src = path.join(process.cwd(), 'manifest.json');
	const dest = path.join(process.cwd(), outDir, 'manifest.json');
	
	try {
		// Make sure the output directory exists.
		fs.mkdirSync(path.join(process.cwd(), outDir), { recursive: true });
		fs.copyFileSync(src, dest);
	} catch (e) {
		console.error('⚠ Failed to copy manifest.json:', e.message);
	}
}

// ==================== Watchers ====================
// Watch manifest.json for changes (debounced, and only on real content changes)
function watchManifest() {
	const manifestPath = path.join(process.cwd(), 'manifest.json');
	
	if (!fs.existsSync(manifestPath)) {
		return;
	}

	let copyTimer = null;
	let lastContent = fs.readFileSync(manifestPath, 'utf8');
	
	fs.watch(manifestPath, () => {
		// Debounce by 100ms.
		if (copyTimer) {
			clearTimeout(copyTimer);
		}
		copyTimer = setTimeout(() => {
			try {
				const newContent = fs.readFileSync(manifestPath, 'utf8');
				// Only copy when the content actually changed.
				if (newContent !== lastContent) {
					lastContent = newContent;
					copyManifest();
				}
			} catch (e) {
				console.error('⚠ Failed to read manifest.json:', e.message);
			}
			copyTimer = null;
		}, 100);
	});
}

// Watch the CSS files for changes
function watchCSS() {
	if (!fs.existsSync(cssRoot)) {
		return;
	}

	let buildTimer = null;
	fs.watch(cssRoot, { recursive: true }, (eventType, filename) => {
		// React to CSS files only.
		if (filename && filename.endsWith('.css')) {
			// Debounce by 100ms.
			if (buildTimer) {
				clearTimeout(buildTimer);
			}
			buildTimer = setTimeout(() => {
				void buildCSS();
				buildTimer = null;
			}, 100);
		}
	});
}

// Create the esbuild context
const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    loader: {
		'.ts': 'ts',
		'.tsx': 'tsx',
		'.json': 'json',
		'.css': 'empty', // ignore CSS imports; styles.css is produced by the buildCSS function above
	},
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
    ],
    format: 'cjs',
    target: 'es2021',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outdir: "dist",
	minify: prod,
    // ...(prod ? { drop: ['console'] } : {}),
});

// ==================== Main ====================
async function main() {
	// Initial build of the CSS and manifest.json.
	await buildCSS();
	copyManifest();

	if (prod) {
		// Production: build once and exit.
		await context.rebuild();
		process.exit(0);
	} else {
		// Dev: start watching.
		watchManifest();
		watchCSS();
		await context.watch();
	}
}

// Run the main function.
main().catch((error) => {
	console.error('Build failed:', error);
	process.exit(1);
});
