import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from 'node:module';
import fs from "node:fs";
import path from "node:path";

// ==================== Constants ====================
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

Dynamic Action Panel - an independent fork of Buttons Panel.

MIT License

Copyright (c) 2025 Kevin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
`;

const prod = process.argv[2] === 'production';
// Opt-in watch mode that also installs into the disposable smoke vault. The
// plain watch build touches nothing outside `dist/`.
const smokeSync = process.argv[2] === 'watch-smoke';
const outDir = "dist";


// Path constants
const cssRoot = path.join(process.cwd(), 'src');
const cssDest = path.join(process.cwd(), outDir, 'styles.css');

// ==================== Helpers ====================
// Recursively collect every CSS file below src
function collectCssFiles(dir) {
	const results = [];
	if (!fs.existsSync(dir)) return results;
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	for (const entry of entries) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			results.push(...collectCssFiles(full));
		} else if (entry.isFile() && entry.name.endsWith('.css')) {
			results.push(full);
		}
	}
	return results;
}

// ==================== Build steps ====================
// Build the CSS: concatenate every CSS file below src into dist/styles.css
// - dev: concatenate and keep the comments, so the output stays readable
// - production: minify through esbuild and drop the comments
async function buildCSS() {
	if (!fs.existsSync(cssRoot)) {
		console.warn('⚠ CSS root directory does not exist: src');
		return;
	}

	const cssFiles = collectCssFiles(cssRoot).sort();
	if (!cssFiles.length) {
		// Without any CSS file, remove a styles.css left over in dist.
		if (fs.existsSync(cssDest)) {
			fs.unlinkSync(cssDest);
			console.log('✓ Removed dist/styles.css (no CSS files in the source directory)');
		}
		return;
	}

	const parts = cssFiles.map((file) => {
		const rel = path.relative(process.cwd(), file);
		const content = fs.readFileSync(file, 'utf8');
		return `/* ${rel} */\n${content}`;
	});
	const combinedCss = parts.join('\n\n');

	try {
		// Make sure the output directory exists.
		fs.mkdirSync(path.join(process.cwd(), outDir), { recursive: true });

		// Transform the CSS through esbuild.
		// - production: minify and drop the comments
		// - dev: no minification, syntax check only
		const result = await esbuild.transform(combinedCss, {
			loader: 'css',
			minify: prod,
			sourcemap: false,
		});

		fs.writeFileSync(cssDest, result.code);
	} catch (error) {
		// On a transform failure, fall back to the unminified version.
		console.error('Error while building the CSS; fell back to the unminified version:', error);
		fs.writeFileSync(cssDest, combinedCss);
	}

	// console.log(`✓ CSS bundled: ${cssDest} (${cssFiles.length} files)`);
}

// Copy manifest.json into the output directory
function copyManifest() {
	const src = path.join(process.cwd(), 'manifest.json');
	const dest = path.join(process.cwd(), outDir, 'manifest.json');
	
	try {
		// Make sure the output directory exists.
		fs.mkdirSync(path.join(process.cwd(), outDir), { recursive: true });
		fs.copyFileSync(src, dest);
	} catch (e) {
		console.error('⚠ Failed to copy manifest.json:', e.message);
	}
}

// ==================== Watchers ====================
// Watch manifest.json for changes (debounced, and only on real content changes)
function watchManifest() {
	const manifestPath = path.join(process.cwd(), 'manifest.json');
	
	if (!fs.existsSync(manifestPath)) {
		return;
	}

	let copyTimer = null;
	let lastContent = fs.readFileSync(manifestPath, 'utf8');
	
	fs.watch(manifestPath, () => {
		// Debounce by 100ms.
		if (copyTimer) {
			clearTimeout(copyTimer);
		}
		copyTimer = setTimeout(() => {
			try {
				const newContent = fs.readFileSync(manifestPath, 'utf8');
				// Only copy when the content actually changed.
				if (newContent !== lastContent) {
					lastContent = newContent;
					copyManifest();
					// esbuild's onEnd does not fire for this file, so the
					// smoke sync has to be triggered here as well.
					if (smokeSync) void syncToSmoke();
				}
			} catch (e) {
				console.error('⚠ Failed to read manifest.json:', e.message);
			}
			copyTimer = null;
		}, 100);
	});
}

// Watch the CSS files for changes
function watchCSS() {
	if (!fs.existsSync(cssRoot)) {
		return;
	}

	let buildTimer = null;
	fs.watch(cssRoot, { recursive: true }, (eventType, filename) => {
		// React to CSS files only.
		if (filename && filename.endsWith('.css')) {
			// Debounce by 100ms.
			if (buildTimer) {
				clearTimeout(buildTimer);
			}
			buildTimer = setTimeout(() => {
				void buildCSS();
				buildTimer = null;
			}, 100);
		}
	});
}

// Create the esbuild context
const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    loader: {
		'.ts': 'ts',
		'.tsx': 'tsx',
		'.json': 'json',
		'.css': 'empty', // ignore CSS imports; styles.css is produced by the buildCSS function above
	},
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
    ],
    format: 'cjs',
    target: 'es2021',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outdir: "dist",
	minify: prod,
    // ...(prod ? { drop: ['console'] } : {}),
	plugins: smokeSync
		? [
				{
					// Fires after every rebuild, which is what makes the smoke
					// vault track the watch loop without a junction.
					name: 'sync-to-smoke',
					setup(build) {
						build.onEnd((result) => {
							if (result.errors.length === 0) {
								void syncToSmoke();
							}
						});
					},
				},
			]
		: [],
});

// ==================== Smoke sync ====================
// The watch loop can keep ONE vault up to date: the disposable smoke vault,
// named explicitly, never taken from the environment. It is opt-in through the
// `watch-smoke` argument, so the plain watch build stays free of side effects.
//
// This replaces the old dev mode, which pointed a junction from the vault at
// `dist/`. That was convenient and wrong: Obsidian then wrote the vault's
// `data.json` INTO the build directory, where a rebuild or a `git clean` could
// take it — and a mistyped path in `.env` aimed the same junction at the
// productive vault. Copying three named files leaves the vault's own state
// where it belongs.

/**
 * Copies the built artifacts into the smoke vault, and reports rather than
 * throws: a watch session must survive a locked file or a half-written build
 * and try again on the next save.
 */
async function syncToSmoke() {
	const { deployToTarget } = await import('./scripts/deployCore.mjs');
	try {
		const manifest = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'manifest.json'), 'utf8'));
		// The same entry point the deploy CLI uses, not a second copy of the
		// sequence: every check, in the same order, including the post-write
		// proof that data.json is unchanged.
		const { pluginDir, written } = deployToTarget({
			targetName: 'smoke',
			distDir: path.join(process.cwd(), 'dist'),
			pluginId: manifest.id,
		});
		// The marker the Hot Reload plugin looks for. It goes in the vault, not
		// in dist, so nothing has to be copied out of a build directory. It is a
		// fourth file, and the only one a deployment writes that is not part of
		// the build — which is why only this watch mode writes it.
		const marker = path.join(pluginDir, '.hotreload');
		if (!fs.existsSync(marker)) fs.writeFileSync(marker, '');
		console.log(`✓ synced to smoke vault: ${written.join(', ')}`);
	} catch (error) {
		// A watch session has to survive a locked file and try again on the next
		// save, so this cannot be fatal. But a refusal is not a transient
		// failure — it means the configuration is wrong and every later sync
		// will fail the same way — so it is shouted rather than mentioned.
		const configProblem = /not an allowed target|is a link|plugin id/.test(error.message);
		console.error(
			configProblem
				? `\n⛔ SMOKE SYNC REFUSED — fix this, it will not resolve itself:\n${error.message}\n`
				: `⚠ smoke sync skipped (will retry on the next rebuild): ${error.message}`
		);
	}
}

// ==================== Main ====================
async function main() {
	// Initial build of the CSS and manifest.json.
	await buildCSS();
	copyManifest();

	if (prod) {
		// Production: build once and exit.
		await context.rebuild();
		process.exit(0);
	} else {
		// Dev: start watching.
		watchManifest();
		watchCSS();
		// The first watch build fires `onEnd` like any other, so the initial
		// sync needs no separate call.
		await context.watch();
	}
}

// Run the main function.
main().catch((error) => {
	console.error('Build failed:', error);
	process.exit(1);
});
