// Build for the Theme Studio, deliberately separate from the panel's and from
// the reader companion's.
//
// It is its own plugin: its own folder in the vault, its own manifest, its own
// data.json. Sharing a build would only couple three things that are meant to
// be able to move apart.
//
// Like the others, this one BUILDS ONLY. It writes into this directory's
// `dist/` and touches no vault. Installing is `scripts/deploySmoke.mjs`.

import esbuild from 'esbuild';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(here, 'dist');
const prod = process.argv[2] === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

Nexus Theme Studio

The live editor for the Nexus theme. It edits nothing but the Nexus design
tokens, stores its state in its own data.json, and leaves the theme's files
alone.

MIT License

Copyright (c) 2026 Max Laska
*/
`;

/**
 * The two files that are copied rather than compiled.
 *
 * styles.css is the editor's OWN chrome — the settings tab's textareas and
 * hints — and has nothing to do with the theme it edits. The theme's CSS is a
 * theme, installed into `.obsidian/themes/` by scripts/deployThemeSmoke.mjs,
 * and is never bundled into this plugin.
 */
const COPIED = ['manifest.json', 'styles.css'];

function copyStaticFiles() {
    fs.mkdirSync(outDir, { recursive: true });
    for (const name of COPIED) {
        fs.copyFileSync(path.join(here, name), path.join(outDir, name));
    }
}

async function main() {
    copyStaticFiles();
    await esbuild.build({
        banner: { js: banner },
        entryPoints: [path.join(here, 'src', 'main.ts')],
        bundle: true,
        external: ['obsidian', 'electron', ...builtinModules],
        format: 'cjs',
        target: 'es2021',
        logLevel: 'info',
        sourcemap: prod ? false : 'inline',
        treeShaking: true,
        minify: prod,
        outfile: path.join(outDir, 'main.js'),
    });
}

main().catch((error) => {
    console.error('Theme Studio build failed:', error);
    process.exit(1);
});
