// Build for the companion plugin, deliberately separate from the panel's.
//
// It is its own bundle with its own entry point and its own output directory,
// because it is its own plugin: Obsidian loads it from its own folder, with its
// own manifest and its own data.json. Sharing a build would only couple two
// things that are meant to be able to move apart.
//
// Like the panel's build, this one BUILDS ONLY. It writes into this directory's
// `dist/` and touches no vault. Installing is `scripts/deploySmoke.mjs`.

import esbuild from 'esbuild';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(here, 'dist');
const prod = process.argv[2] === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

ZotFlow Reader Extensions

A companion plugin for the reader ZotFlow embeds. It is not affiliated with
ZotFlow or with Zotero, contains no code from either, and patches neither: it
adjusts the reader's own DOM from outside at runtime.

MIT License

Copyright (c) 2026 Max Laska
*/
`;

/**
 * The two files that are copied rather than compiled.
 *
 * styles.css is hand-written and shipped as-is: it is the half of this plugin's
 * CSS that applies to OBSIDIAN's workspace, which Obsidian loads from the
 * plugin folder itself. The other half belongs to the reader's iframe, which no
 * stylesheet loader can reach, and is injected at runtime instead.
 */
const COPIED = ['manifest.json', 'styles.css'];

function copyStaticFiles() {
    fs.mkdirSync(outDir, { recursive: true });
    for (const name of COPIED) {
        fs.copyFileSync(path.join(here, name), path.join(outDir, name));
    }
}

async function main() {
    copyStaticFiles();
    await esbuild.build({
        banner: { js: banner },
        entryPoints: [path.join(here, 'src', 'main.ts')],
        bundle: true,
        external: ['obsidian', 'electron', ...builtinModules],
        format: 'cjs',
        target: 'es2021',
        logLevel: 'info',
        sourcemap: prod ? false : 'inline',
        treeShaking: true,
        minify: prod,
        outfile: path.join(outDir, 'main.js'),
    });
}

main().catch((error) => {
    console.error('Companion build failed:', error);
    process.exit(1);
});
